theme: jekyll-theme-minimal
title: Lakshmi J. Naik
description: PhD student in theoretical high energy physics

#plugins:
#  - jekyll-scholar
  
#scholar:
#  bibliography: INSPIRE-CiteAll.bib
  #bibliography_template: bib
#  source: _bibliography
